NovelNest/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include("home.urls")),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views


urlpatterns = [     
    path("home/", views.home, name="home"),
    path("login/", views.user_login, name="login"),
    path("", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("register/", views.user_register, name="register"),
    path("update_user/", views.update_user, name="update_user"),
    path("books/", views.get_books, name="books"),
    path("genres/", views.get_genres, name="genres"),
    path('get_book/<int:book_id>/', views.get_specific_book, name="get_book"),
    path("download_book/<int:book_id>", views.download_pdf,name="download_book"),
    path('get_book_content/<int:book_id>', views.get_book_content, name="get_book_content"),
    path('get_book_page/<int:book_id>/page/<int:page_number>/', views.get_book_page, name="get_book_page"),
    path('collection/', views.collection, name="collection"),
]

home/models.py
from django.db import models    
from django.contrib.auth.models import User
from django.utils import timezone

genre_list = [('literature','Literature'),('romance', 'Romance'), ('thriller', 'Thriller'),('novel', 'Novel'),('fiction','Fiction'),('fantasy','Fantasy'),('mystery','Mystery')]

class Genre(models.Model):
    name = models.CharField(choices=genre_list ,blank=False,max_length=25)
    image = models.ImageField(upload_to='genre-thumbnails/')
    
    def __str__(self):
        return self.get_name_display()

class Book(models.Model):
    name = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    summary = models.TextField()
    publication_year = models.PositiveIntegerField()
    genres = models.ManyToManyField(Genre, related_name='books')
    pdf_file = models.FileField(upload_to='ebooks/')
    thumbnail = models.ImageField(upload_to='ebooks/thumbnails/', blank=True,null=True)
    added_date = models.DateTimeField(auto_now_add=True)
    language = models.CharField(max_length=20,default="English")
    rating = models.SmallIntegerField(default=None)
    pages = models.IntegerField(default=None)
    
    def __str__(self):
        return f"{self.name} by {self.author}"
    
class ReadList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    read = models.DateTimeField(default=timezone.now)
    
    class Meta:
        unique_together = ('user','book')
    
class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, related_name='profile')
    favourite_genres = models.ManyToManyField(Genre,related_name='favorite_genres',blank=True) 
    profile_picture = models.ImageField(upload_to='profile_pics/',default='profile_pics/default.png')
    phone_number = models.CharField(max_length=15,unique=True, default=0)
    books_read = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return f"{self.user.username}"


class Collection(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    added_on = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = ('user','book')    
    
    def __str__(self):
        return f"{self.user.username}'s Collection"        

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=True, max_length=30)
    last_name = forms.CharField(required=True, max_length=30)
    profile_picture = forms.ImageField(required=True)
    phone_number = forms.CharField(max_length=15, required=False)
    
    class Meta:
        model = User
        fields = ["username","first_name","last_name","email","password1","password2"]
        
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ["phone_number","profile_picture"] 

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name","last_name","email"]

home/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import *
from django.core.cache import cache
from django.http import JsonResponse,FileResponse,HttpResponse
from PyPDF2 import PdfReader
from django.contrib import messages
from django.contrib.auth.models import User
import os, fitz
from io import BytesIO
from PIL import Image
from NovelNest.settings import MEDIA_URL
from django.contrib.auth import  login,logout,authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from .forms import *

@login_required
def home(request):
    # print(request.user.id)
    colors = [c for c in range(200, 900, 100)]
    books = Book.objects.all().order_by('-added_date')[:6] 
    genres = Genre.objects.all()[:6]
    
    books_with_colors = [{'color': colors[i % len(colors)], 'book': book} for i, book in enumerate(books)]
    genres_with_colors = [{'color': colors[i % len(colors)], 'genre': genre} for i, genre in enumerate(genres)]
    
    return render(request, 'index.html', {
        'books_with_colors': books_with_colors,
        'genres_with_colors': genres_with_colors,
    })

def user_login(request):
    if request.user.is_authenticated:
        return redirect('home')
    
    if request.method == "POST":
        
        login_id = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(request, username=login_id, password=password)
        
        if user is None:
            try:
                profile = UserProfile.objects.get(phone_number=login_id)
                user = authenticate(request, username=profile.user.username, password=password)
            except Exception as error:
                user = None
        
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            return render(request, 'login.html', {
                'form': AuthenticationForm(),
                'error': 'Invalid credentials.'
            })
                
        # form = AuthenticationForm(request, data=request.POST)
        # if form.is_valid():
        #     user=form.get_user()
        #     login(request,user)
        #     return redirect('home')
        # else:
        #     return render(request, 'login.html', {'form': form, 'error': 'Invalid username or password'})
    return render(request, 'login.html', {'form': AuthenticationForm()})

@login_required
def user_logout(request):
    logout(request)
    return redirect('login')

@login_required
def update_user(request):
    
    user = request.user
    profile = user.profile

    if request.method == "POST":
        user_form = UserUpdateForm(request.POST,instance=user)
        profile_form = UserProfileForm(request.POST, request.FILES, instance=profile)

        if user_form.is_valid() and profile_form.is_valid() :
            user_form.save()
            profile_form.save()
            
            messages.success(request,"Your Profile has been updated")
            return redirect('update_user')
        else :
            messages.error(request, "Error in Updating Profile")
            return redirect('update_user')
    else :
        user_form = UserUpdateForm(instance=user)
        profile_form = UserProfileForm(instance=profile)
    
    return render(request, 'edit_profile.html',{
        "user" : request.user,
        "user_form" : user_form,
        "profile_form" : profile_form
    })

def user_register(request):
    if request.user.is_authenticated:
        return redirect('home')
    if request.method == 'POST':
        form = UserRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            phone_number = form.cleaned_data["phone_number"]
            profile_picture = form.cleaned_data.get("profile_picture")
            UserProfile.objects.create(
                user=user,
                phone_number = phone_number,
                profile_picture = profile_picture
            )
            
        # username = request.POST.get('username')
        # firstname = request.POST.get('firstname')
        # lastname = request.POST.get('lastname')
        # email = request.POST.get('email')
        # password = request.POST.get('password')
        
        # user_existing = User.objects.filter(username=username).first()
        # if user_existing :
        #     return JsonResponse({"error":"User already exists"}, status=500) 
        
        # user = User.objects.create_user(username,email,password)
        # user.first_name = firstname
        # user.last_name = lastname
        # user.save()
        
            return redirect('login')
    else:
        form = UserRegisterForm()
            
    return render(request, 'register.html',{"form" : form})

@login_required
def get_books(request):
    books = Book.objects.all()
    return render(request,'books_admin.html',{'books':books})

def get_specific_book(request,book_id):
    
    book = Book.objects.filter(id=book_id).first()
    suggestions = Book.objects.exclude(id=book_id)
        
    return render(request,'book.html',{"book":book,'suggestions':suggestions})

@login_required
def download_pdf(request,book_id):
    book = Book.objects.filter(id=book_id).first()
    file_path = book.pdf_file.path
    if os.path.exists(file_path):
        return FileResponse(open(file_path,'rb'), as_attachment=True, filename=f"{book.name}.pdf")

@login_required
def get_genres(request):
    genres = Genre.objects.all()
    return render(request,'genre.html',{'genres':genres})

def get_book_page(request, book_id=None, page_number=None):
    
    cache_key = f"book_{book_id}_page_{page_number}"
    cached_img = cache.get(cache_key)
    if cached_img:
        return HttpResponse(cached_img, content_type='image/png')
    
    try:
        book = get_object_or_404(Book, id=book_id)
        pdf_path = book.pdf_file.path
        
        doc = fitz.open(pdf_path)
        page = doc.load_page(page_number)
        pix = page.get_pixmap()
        img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)

        img_byte_arr = BytesIO()
        img.save(img_byte_arr, format='PNG')
        img_byte_arr.seek(0)
        
        cache.set(cache_key, img_byte_arr.getvalue(), timeout=300)

        return HttpResponse(img_byte_arr, content_type='image/png')
        
    except Exception as e:
        print(e)
        return JsonResponse({"error": str(e)}, status=500)

def get_book_content(request, book_id):
    
    book = get_object_or_404(Book,id=book_id)
    
    with open(book.pdf_file.path,'rb') as f:
        reader = PdfReader(f)
        return render(request,'read_book.html', {
            "page_length" : len(reader.pages),
            "book" : book
        })

def collection(request):
    
    if request.method == "POST" :
        book_id = request.POST.get('book_id')
        book = get_object_or_404(Book,id=book_id)
        collection = Collection.objects.create(
            user = request.user,
            book = book
        )
        collection.save()
        return JsonResponse()
    else:
        return render(request, 'collection.html')

    

def user_profile(request,username):
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(UserProfile,user=user)
    readlist = get_object_or_404(ReadList,user=user)
    
    return render(request, 'user_profile.html' , {'profile':profile, 'readlist' : readlist})

def book_suggestions(request):
    user = request.user
    favourite_genres = UserProfile.objects.filter(user=user).values_list('favourite_genres__name')
    collection = Collection.objects.filter(user=user).values_list('book', flat=True)

    return render(request, 'index.html',{'favourite_genres':favourite_genres,'collection':collection})

home/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" style="background-color: #0d061f; color: #ffffff;">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">
  <link rel="icon" type="image/x-icon" href="{% static 'images/logo.ico' %}">
  <link rel="stylesheet" href="{% static 'css/home.css' %}">
  <title>{% block title %}NovelNest{% endblock %}</title>

  <style>
    /* Apply gradient background to the sidebar */
    *{
      font-family: "system-ui";
    }

    .sidebar {
      background: linear-gradient(to right, #0d061f, rgba(13, 6, 31, 0));
      /* Dark to transparent gradient */
      transition: width 0.3s ease-in-out;
      color: #ffffff;
    }

    .sidebar:hover {
      width: 160px;
      /* Sidebar expands on hover */
    }

    /* Style for the sidebar content */
    .sidebar .group:hover {
      background-color: rgba(0, 0, 0, 0.3);
      width: 100%;
      /* Slight background change on hover */
    }
  </style>
</head>

<body class="h-screen bg-transparent overflow-x-hidden">

  <div class="flex-wrap gap-2">
    <div
      class="pr-2 sidebar fixed top-0 flex flex-col items-center absolute w-16 h-full overflow-hidden text-gray-400 bg-gray-900 rounded group transition-all duration-300 ease-in-out z-10">
      <!-- Sidebar Icon and Text Section -->
      <a class="flex items-center justify-center mt-3 p-2 w-full">
        <svg class="w-8 h-8 fill-current group-hover:text-white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"
          fill="currentColor">
          <path
            d="M11 17a1 1 0 001.447.894l4-2A1 1 0 0017 15V9.236a1 1 0 00-1.447-.894l-4 2a1 1 0 00-.553.894V17zM15.211 6.276a1 1 0 000-1.788l-4.764-2.382a1 1 0 00-.894 0L4.789 4.488a1 1 0 000 1.788l4.764 2.382a1 1 0 00.894 0l4.764-2.382zM4.447 8.342A1 1 0 003 9.236V15a1 1 0 00.553.894l4 2A1 1 0 009 17v-5.764a1 1 0 00-.553-.894l-4-2z" />
        </svg>
        <span class="ml-2 text-sm font-bold group-hover:block hidden">NovelNest</span>
      </a>

      <!-- Sidebar Links -->
      <div class="flex flex-col items-center mt-3 border-t border-gray-700 w-full">
        <a href="{%url 'home'%}" class="flex items-center justify-center w-12 h-12 mt-2 rounded group hover:text-gray-300" id="Home">
          <svg class="w-6 h-6 stroke-current" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
            stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
          </svg>
          <span class="ml-2 text-sm font-medium group-hover:block  hidden">Home</span>
        </a>

        <a class="flex items-center justify-center w-12 h-12 mt-2 rounded group hover:text-gray-300" id="Search">
          <svg class="w-6 h-6 stroke-current" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
            stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
          </svg>
          <span class="ml-2 text-sm font-medium group-hover:block hidden">Search</span>
        </a>

        <a class="flex items-center justify-center w-12 h-12 mt-2 rounded group hover:text-gray-300" id="Genres">
          <svg class="w-6 h-6 stroke-current group-hover:text-white" xmlns="http://www.w3.org/2000/svg" fill="none"
            viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6H20M4 12H20M4 18H20" />
          </svg>
          <span class="ml-2 text-sm font-medium group-hover:block hidden">Genres</span>
        </a>

        <a href="{% url 'collection' %}" class="flex items-center justify-center w-12 h-12 mt-2 rounded group hover:text-gray-300" id="Collection">
          <svg class="w-6 h-6 stroke-current" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
            stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M5 3h14a2 2 0 012 2v14l-7-5-7 5V5a2 2 0 012-2z" />
          </svg>
          <span class="ml-2 text-sm font-medium group-hover:block hidden">Collection</span>
        </a>

        <a class="flex items-center justify-center w-12 h-12 mt-2 rounded group hover:text-gray-300" id="Logout"
          href="{% url 'logout' %}">

          <svg class="w-6 h-6 group-hover:hidden pl-1" xmlns="http://www.w3.org/2000/svg" height="12" width="12"
            viewBox="0 0 512 512">
            <path fill="#ffffff"
              d="M377.9 105.9L500.7 228.7c7.2 7.2 11.3 17.1 11.3 27.3s-4.1 20.1-11.3 27.3L377.9 406.1c-6.4 6.4-15 9.9-24 9.9c-18.7 0-33.9-15.2-33.9-33.9l0-62.1-128 0c-17.7 0-32-14.3-32-32l0-64c0-17.7 14.3-32 32-32l128 0 0-62.1c0-18.7 15.2-33.9 33.9-33.9c9 0 17.6 3.6 24 9.9zM160 96L96 96c-17.7 0-32 14.3-32 32l0 256c0 17.7 14.3 32 32 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32l-64 0c-53 0-96-43-96-96L0 128C0 75 43 32 96 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32z" />
          </svg>
          <span class="ml-2 text-sm font-medium group-hover:block hidden">Logout</span>
        </a>



      </div>
    </div>

    <div>
      {% block content %}
      {% endblock %}
    </div>

  </div>

  <script src="{% static 'js/home.js' %}"></script>
</body>

</html>

home/templates/book.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Book {% endblock %}

{% block content %}

{% if block %}

<div class="bg-[#0d061f] text-white">

    <div class="container mx-auto px-4 py-8">

        <div class="flex flex-col md:flex-row gap-8">

            <div
                class="w-full md:w-2/5 bg-gray-800 rounded-lg shadow-lg overflow-hidden transition-transform transform hover:scale-105 hover:shadow-xl p-6 fixed max-h-9/10  mb-2">
                <div class="flex flex-col items-center text-center">
                    <button class="ml-90 ">add</button>
                    <div class="relative w-3/4 h-70 mb-6">
                            <img src="{{ book.thumbnail.url }}" alt="Book Cover"
                                class="absolute inset-0 w-full h-full object-contain rounded-lg"
                                style="pointer-events: none;">
                    </div>

                    <h2 class="text-3xl font-extrabold text-white mb-4">{{ book.name }}</h2>
                    <p class="text-lg font-light text-gray-400 mb-4">By {{ book.author }}</p>
                </div>
                <div class="overflow-y-auto">
                    <span>{{book.summary}}</span>
                </div>
                <div class="mt-5">
                    <a href="{% url 'get_book_content' book.id %}">Read Now ></a>
                    <a href="{% url 'download_book' book_id=book.id %}" class="ml-60" download> Download Ebook</a>
                </div>
            </div>

            <div class="ml-[40%] md:w-3/5 overflow-y-auto max-h-screen pr-4">
                <div>
                    <h3 class="text-xl font-semibold text-white mb-4 ml-20">More Books You May Like</h3>

                    <div class="flex flex-col space-y-6">

                        {% for suggestion in suggestions %}
                        <div
                            class="bg-gray-800 p-6 rounded-lg shadow-lg hover:scale-105 hover:shadow-xl transition-transform w-[80%] h-48 mx-auto">
                            <a href="{% url 'get_book' suggestion.id  %}">
                                <div class="flex h-full">
                                    <img src="{{ suggestion.thumbnail.url }}" alt="Book Cover"
                                        class="w-1/5 h-full object-cover rounded-md mr-6">
                                    <div class="flex flex-col justify-between w-2/3">
                                        <p class="text-sm font-semibold text-white">{{suggestion.name}}</p>
                                        <p class="text-xs text-gray-400">By {{ suggestion.author }}</p>
                                        <p class="text-gray-300 text-sm">{{suggestion.summary}}</p>
                                    </div>

                                </div>
                            </a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>

</script>
{% endif %}

{% endblock %}

home/templates/books_admin.html
{% extends 'base.html' %}
{% load static %}

{% block title %}NovelNest-Home{% endblock %}

{% block content %}

<div class="justify-center flex items-center w-full">
    <span class="justify-self-center font-serif m-7 mt-15 text-[40px]">Books</span>
</div>

<div class="flex flex-wrap justify-start mt-5 ml-16">
    {% for book in books %}
    <div class="flex justify-center items-center m-3">
        <div
            class="max-w-sm w-full h-[250px] container bg-white rounded-2xl shadow-lg transform transition duration-500 hover:scale-105 hover:shadow-2xl flex flex-col">
            <a href="{% url 'get_book' book.id  %}">
                <img class="w-full h-[200px] object-cover cursor-pointer rounded-t-2xl" src="{{ book.thumbnail.url }}"
                    alt="{{ book.title }}" />
            </a>
            <div class="flex p-4 justify-between flex-grow">
                <div class="flex items-center space-x-1">
                    <h2 class="text-gray-800 font-bold cursor-pointer">By {{book.author}}</h2>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

home/templates/collection.html
{% extends 'base.html' %}
{% load static %}

{% block title %}NovelNest-Home{% endblock %}

{% block content %}
<p>HELLO COLLECTION</p>
{% endblock %}

home/templates/edit_profile.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" />
    <link rel="icon" type="image/x-icon" href="{% static 'images/logo.ico' %}" />
    <link rel="stylesheet" href="{% static 'css/home.css' %}" />
    <title>
      {% block title %}
        Edit Profile | NovelNest
      {% endblock %}
    </title>
  </head>
  <body>


    <div class="flex h-screen bg-indigo-950">
      <div class="w-full max-w-4xl m-auto bg-zinc-100 rounded p-5 shadow-lg">
        <header>
          <img class="w-20 mx-auto mb-5" src="{% static 'images/logo.ico' %}" alt="Logo" />
        </header>
        <h2 class="text-2xl font-bold text-center text-indigo-900 mb-4">Edit Your Profile</h2>

        <form method="post" enctype="multipart/form-data" class="space-y-6">
          {% csrf_token %}

          {% if user_form.non_field_errors or profile_form.non_field_errors %}
            <div class="text-red-500 text-sm mb-4">
              {% for error in user_form.non_field_errors %}
                <p>{{ error }}</p>
              {% endfor %}
              {% for error in profile_form.non_field_errors %}
                <p>{{ error }}</p>
              {% endfor %}
            </div>
          {% endif %}

          <!-- Profile Picture Section with Edit Icon -->
          <div class="flex justify-center relative mb-4">
            {% if user.profile.profile_picture %}
              <img src="{{ user.profile.profile_picture.url }}" alt="Profile Picture" class="w-24 h-24 rounded-full object-cover shadow-md" />
              <!-- Edit icon shown only on hover -->
              <label for="id_profile_picture" class="absolute bottom-0 right-0 bg-indigo-700 text-white p-2 rounded-full cursor-pointer hover:bg-pink-700 transition duration-300 ease-in-out"><i class="fas fa-pen"></i></label>
            {% else %}
              <div class="w-24 h-24 rounded-full bg-gray-300 flex justify-center items-center text-white font-bold">
                <i class="fas fa-camera"></i>
              </div>
            {% endif %}
          </div>

          <h2 class="text-2xl font-bold text-center text-indigo-900 mb-4">{{ user.username }}</h2>

          <!-- Profile Picture File Input (Hidden) -->
          <input type="file" id="id_profile_picture" name="profile_picture" class="hidden" accept="image/*" />
          
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <!-- User Form Fields -->
            {% for field in user_form %}
              <div>
                <label for="{{ field.id_for_label }}" class="block mb-2 text-stone-900 font-semibold">{{ field.label }}</label>
                {{ field|add_class:'w-full px-4 py-2 border border-zinc-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition duration-300 ease-in-out text-gray-800 placeholder-gray-500' }}
                {% for error in field.errors %}
                  <p class="text-red-600 text-sm mt-1">{{ error }}</p>
                {% endfor %}
              </div>
            {% endfor %}

            <!-- Phone Number -->
            <div>
              <label for="id_phone_number" class="block mb-2 text-stone-900 font-semibold">Phone Number</label>
              {{ profile_form.phone_number|add_class:'w-full px-4 py-2 border border-zinc-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition duration-300 ease-in-out text-gray-800 placeholder-gray-500' }}
              {% for error in profile_form.phone_number.errors %}
                <p class="text-red-600 text-sm mt-1">{{ error }}</p>
              {% endfor %}
            </div>
          </div>

          <div class="flex justify-center mt-6">
            <button type="submit" class="w-40 h-10 bg-indigo-700 hover:bg-pink-700 text-white font-bold px-4 py-2 rounded transition duration-300 ease-in-out hover:scale-105">Update Profile</button>
          </div>
        </form>
      </div>
    </div>
  </body>
</html>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  
</body>
</html>

home/templates/genre.html
{% extends 'base.html' %}
{% load static %}

{% block title %}NovelNest-Home{% endblock %}

{% block content %}

<div class="justify-center flex items-center w-full">
    <span class="justify-self-center font-serif m-7 mt-15 text-[40px]">Genres</span>
</div>

<div class="flex flex-wrap justify-start mt-5 ml-10">
    {% for genre in genres %}
    <div class="flex justify-center items-center m-3">
        <div
            class="w-[180px] h-[250px] container bg-white rounded-2xl shadow-lg transform transition duration-500 hover:scale-105 hover:shadow-2xl flex flex-col">
            <a href="#">
                <img class="w-full h-[200px] object-cover cursor-pointer rounded-t-2xl" src="{{ genre.image.url }}"
                    alt="{{ genre.name }}" />
            </a>
            <div class="flex p-4 justify-between flex-grow">
                <div class="flex items-center space-x-1">
                    <h2 class="text-gray-800 font-bold cursor-pointer">{{genre.get_name_display }}</h2>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}